### ISSUE TITLE
Price doesn't update exactly on the hour

### ISSUE THREAD

**Issue by MattDahEpic** [MattDahEpic/ha-midas#33]
Most rates have rate info items that start and end on hour boundaries and while the general vibe of the times are right (a rate that changes at 4pm will change around 4pm) I'd really like it to update right at 4pm.
Is there a way to force HA to update an entity right on that hour boundary? We have the time it will occur in advance, and we can schedule one right on the hour boundary if we want too. It seems like it updates within 15 minutes currently. Could it be related to the data coordinator update time?

**Comment by breakthestatic** [comment]
Could explicitly calling `homeassistant.update_entity` via an hourly (on the hour) cron automation be a temporary workaround until this is resolved? E.g.
```
triggers:
  - trigger: time_pattern
    hours: /1
actions:
  - action: homeassistant.update_entity
    metadata: {}
    data:
      entity_id:
        - sensor.current_tariff_name
        - sensor.current_energy_price
```
I just noticed this myself today and have implemented the above. I'll report back if it works as a short-term solution until the actual bug gets fixed.
